/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path');

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim();
      return readFileSync(lddPath, 'utf8').includes('musl');
    } catch (e) {
      return true;
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header;
    return !glibcVersionRuntime;
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'tempoch.android-arm64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.android-arm64.node');
          } else {
            nativeBinding = require('@siderust/tempoch-android-arm64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'tempoch.android-arm-eabi.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.android-arm-eabi.node');
          } else {
            nativeBinding = require('@siderust/tempoch-android-arm-eabi');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`);
    }
    break;
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'tempoch.win32-x64-msvc.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.win32-x64-msvc.node');
          } else {
            nativeBinding = require('@siderust/tempoch-win32-x64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'ia32':
        localFileExisted = existsSync(join(__dirname, 'tempoch.win32-ia32-msvc.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.win32-ia32-msvc.node');
          } else {
            nativeBinding = require('@siderust/tempoch-win32-ia32-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'tempoch.win32-arm64-msvc.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.win32-arm64-msvc.node');
          } else {
            nativeBinding = require('@siderust/tempoch-win32-arm64-msvc');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`);
    }
    break;
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'tempoch.darwin-universal.node'));
    try {
      if (localFileExisted) {
        nativeBinding = require('./tempoch.darwin-universal.node');
      } else {
        nativeBinding = require('@siderust/tempoch-darwin-universal');
      }
      break;
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'tempoch.darwin-x64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.darwin-x64.node');
          } else {
            nativeBinding = require('@siderust/tempoch-darwin-x64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'tempoch.darwin-arm64.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.darwin-arm64.node');
          } else {
            nativeBinding = require('@siderust/tempoch-darwin-arm64');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`);
    }
    break;
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`);
    }
    localFileExisted = existsSync(join(__dirname, 'tempoch.freebsd-x64.node'));
    try {
      if (localFileExisted) {
        nativeBinding = require('./tempoch.freebsd-x64.node');
      } else {
        nativeBinding = require('@siderust/tempoch-freebsd-x64');
      }
    } catch (e) {
      loadError = e;
    }
    break;
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-x64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-x64-musl.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-x64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-x64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-x64-gnu.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-x64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-arm64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-arm64-musl.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-arm64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-arm64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-arm64-gnu.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-arm64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-arm-musleabihf.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-arm-musleabihf.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-arm-musleabihf');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-arm-gnueabihf.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-arm-gnueabihf.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-arm-gnueabihf');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-riscv64-musl.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-riscv64-musl.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-riscv64-musl');
            }
          } catch (e) {
            loadError = e;
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'tempoch.linux-riscv64-gnu.node'));
          try {
            if (localFileExisted) {
              nativeBinding = require('./tempoch.linux-riscv64-gnu.node');
            } else {
              nativeBinding = require('@siderust/tempoch-linux-riscv64-gnu');
            }
          } catch (e) {
            loadError = e;
          }
        }
        break;
      case 's390x':
        localFileExisted = existsSync(join(__dirname, 'tempoch.linux-s390x-gnu.node'));
        try {
          if (localFileExisted) {
            nativeBinding = require('./tempoch.linux-s390x-gnu.node');
          } else {
            nativeBinding = require('@siderust/tempoch-linux-s390x-gnu');
          }
        } catch (e) {
          loadError = e;
        }
        break;
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`);
    }
    break;
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError;
  }
  throw new Error(`Failed to load native binding`);
}

const {
  JulianDate,
  ModifiedJulianDate,
  Period,
  jdToMjd,
  mjdToJd,
  julianCenturies,
  julianYears,
  jdFromDate,
  mjdFromDate,
  jdToDate,
  mjdToDate,
  jdDifference,
  mjdDifference,
  version,
} = nativeBinding;

module.exports.JulianDate = JulianDate;
module.exports.ModifiedJulianDate = ModifiedJulianDate;
module.exports.Period = Period;
module.exports.jdToMjd = jdToMjd;
module.exports.mjdToJd = mjdToJd;
module.exports.julianCenturies = julianCenturies;
module.exports.julianYears = julianYears;
module.exports.jdFromDate = jdFromDate;
module.exports.mjdFromDate = mjdFromDate;
module.exports.jdToDate = jdToDate;
module.exports.mjdToDate = mjdToDate;
module.exports.jdDifference = jdDifference;
module.exports.mjdDifference = mjdDifference;
module.exports.version = version;
